# Use an official Python image
FROM python:3.13

# Set working directory
WORKDIR /app

# Copy your code and requirements
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

# Run your script
CMD ["python", "src/python/titanic_python.py"]
